In [ ]:
import numpy as np

## Numpy

*   Library for mathematical and numerical functions.
*   np.array() function makes an array out of no. of elements.

## Arrays in Numpy

*   Same data type of all elements unlike list

In [ ]:
arr=np.array([1,2,3,4,5,6])

print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>

.shape gives the dimension of the array

In [ ]:
arr.shape

(6,)

## Dimensions of Numpy

    1. 0 Dimension: Collection of a single element
        *   Ex. np.array(5)

In [ ]:
a=np.array(5)
print(a)

5

    2. 1 Dimension: Collection of 0 dimension arrays
        *   np.array([1,2,3])

In [ ]:
b=np.array([1,2,3])
print(b)

[1 2 3]

    3. 2 Dimension: Collection of 1 dimension arrays
        *   np.array([[1,2,3],[4,5,6]])

In [ ]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]

    4. 3 Dimension: Collection of 2 dimension arrays
        *   np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

## Pandas

*   Used to make csv or json files to dataframes.
*   Used for working with a dataset for data cleaning and analysis.

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('Titanic.csv')

Dataframes is a data structure with row and column in tabular form.

.loc[idx] function returns the row at 'idx' index.

In [ ]:
df.loc[0]

Unnamed: 0               0
survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

In [ ]:
df.loc[0:3] #Prints 0th, 1st, 2nd and 3rd row

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False

In [ ]:
print(df) #prints first 5 and last 5 rows

     Unnamed: 0  survived  pclass     sex   age  sibsp  parch     fare  \
0             0         0       3    male  22.0      1      0   7.2500
1             1         1       1  female  38.0      1      0  71.2833
2             2         1       3  female  26.0      0      0   7.9250
3             3         1       1  female  35.0      1      0  53.1000
4             4         0       3    male  35.0      0      0   8.0500
..          ...       ...     ...     ...   ...    ...    ...      ...
886         886         0       2    male  27.0      0      0  13.0000
887         887         1       1  female  19.0      0      0  30.0000
888         888         0       3  female   NaN      1      2  23.4500
889         889         1       1    male  26.0      0      0  30.0000
890         890         0       3    male  32.0      0      0   7.7500

    embarked   class    who  adult_male deck  embark_town alive  alone
0          S   Third    man        True  NaN  Southampton    no  False
1          C   First  woman       False    C    Cherbourg   yes  False
2          S   Third  woman       False  NaN  Southampton   yes   True
3          S   First  woman       False    C  Southampton   yes  False
4          S   Third    man        True  NaN  Southampton    no   True
..       ...     ...    ...         ...  ...          ...   ...    ...
886        S  Second    man        True  NaN  Southampton    no   True
887        S   First  woman       False    B  Southampton   yes   True
888        S   Third  woman       False  NaN  Southampton    no  False
889        C   First    man        True    C    Cherbourg   yes   True
890        Q   Third    man        True  NaN   Queenstown    no   True

[891 rows x 16 columns]

In [ ]:
print(df.to_string())

     Unnamed: 0  survived  pclass     sex    age  sibsp  parch      fare embarked   class    who  adult_male deck  embark_town alive  alone
0             0         0       3    male  22.00      1      0    7.2500        S   Third    man        True  NaN  Southampton    no  False
1             1         1       1  female  38.00      1      0   71.2833        C   First  woman       False    C    Cherbourg   yes  False
2             2         1       3  female  26.00      0      0    7.9250        S   Third  woman       False  NaN  Southampton   yes   True
3             3         1       1  female  35.00      1      0   53.1000        S   First  woman       False    C  Southampton   yes  False
4             4         0       3    male  35.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
5             5         0       3    male    NaN      0      0    8.4583        Q   Third    man        True  NaN   Queenstown    no   True
6             6         0       1    male  54.00      0      0   51.8625        S   First    man        True    E  Southampton    no   True
7             7         0       3    male   2.00      3      1   21.0750        S   Third  child       False  NaN  Southampton    no  False
8             8         1       3  female  27.00      0      2   11.1333        S   Third  woman       False  NaN  Southampton   yes  False
9             9         1       2  female  14.00      1      0   30.0708        C  Second  child       False  NaN    Cherbourg   yes  False
10           10         1       3  female   4.00      1      1   16.7000        S   Third  child       False    G  Southampton   yes  False
11           11         1       1  female  58.00      0      0   26.5500        S   First  woman       False    C  Southampton   yes   True
12           12         0       3    male  20.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
13           13         0       3    male  39.00      1      5   31.2750        S   Third    man        True  NaN  Southampton    no  False
14           14         0       3  female  14.00      0      0    7.8542        S   Third  child       False  NaN  Southampton    no   True
15           15         1       2  female  55.00      0      0   16.0000        S  Second  woman       False  NaN  Southampton   yes   True
16           16         0       3    male   2.00      4      1   29.1250        Q   Third  child       False  NaN   Queenstown    no  False
17           17         1       2    male    NaN      0      0   13.0000        S  Second    man        True  NaN  Southampton   yes   True
18           18         0       3  female  31.00      1      0   18.0000        S   Third  woman       False  NaN  Southampton    no  False
19           19         1       3  female    NaN      0      0    7.2250        C   Third  woman       False  NaN    Cherbourg   yes   True
20           20         0       2    male  35.00      0      0   26.0000        S  Second    man        True  NaN  Southampton    no   True
21           21         1       2    male  34.00      0      0   13.0000        S  Second    man        True    D  Southampton   yes   True
22           22         1       3  female  15.00      0      0    8.0292        Q   Third  child       False  NaN   Queenstown   yes   True
23           23         1       1    male  28.00      0      0   35.5000        S   First    man        True    A  Southampton   yes   True
24           24         0       3  female   8.00      3      1   21.0750        S   Third  child       False  NaN  Southampton    no  False
25           25         1       3  female  38.00      1      5   31.3875        S   Third  woman       False  NaN  Southampton   yes  False
26           26         0       3    male    NaN      0      0    7.2250        C   Third    man        True  NaN    Cherbourg    no   True
27           27         0       1    male  19.00      3      2  263.0000        S   First    man        True    C  Southampton    no  False
28           28         1       3  female    NaN      0      0    7.8792        Q   Third  woman       False  NaN   Queenstown   yes   True
29           29         0       3    male    NaN      0      0    7.8958        S   Third    man        True  NaN  Southampton    no   True
30           30         0       1    male  40.00      0      0   27.7208        C   First    man        True  NaN    Cherbourg    no   True
31           31         1       1  female    NaN      1      0  146.5208        C   First  woman       False    B    Cherbourg   yes  False
32           32         1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN   Queenstown   yes   True
33           33         0       2    male  66.00      0      0   10.5000        S  Second    man        True  NaN  Southampton    no   True
34           34         0       1    male  28.00      1      0   82.1708        C   First    man        True  NaN    Cherbourg    no  False
35           35         0       1    male  42.00      1      0   52.0000        S   First    man        True  NaN  Southampton    no  False
36           36         1       3    male    NaN      0      0    7.2292        C   Third    man        True  NaN    Cherbourg   yes   True
37           37         0       3    male  21.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
38           38         0       3  female  18.00      2      0   18.0000        S   Third  woman       False  NaN  Southampton    no  False
39           39         1       3  female  14.00      1      0   11.2417        C   Third  child       False  NaN    Cherbourg   yes  False
40           40         0       3  female  40.00      1      0    9.4750        S   Third  woman       False  NaN  Southampton    no  False
41           41         0       2  female  27.00      1      0   21.0000        S  Second  woman       False  NaN  Southampton    no  False
42           42         0       3    male    NaN      0      0    7.8958        C   Third    man        True  NaN    Cherbourg    no   True
43           43         1       2  female   3.00      1      2   41.5792        C  Second  child       False  NaN    Cherbourg   yes  False
44           44         1       3  female  19.00      0      0    7.8792        Q   Third  woman       False  NaN   Queenstown   yes   True
45           45         0       3    male    NaN      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
46           46         0       3    male    NaN      1      0   15.5000        Q   Third    man        True  NaN   Queenstown    no  False
47           47         1       3  female    NaN      0      0    7.7500        Q   Third  woman       False  NaN   Queenstown   yes   True
48           48         0       3    male    NaN      2      0   21.6792        C   Third    man        True  NaN    Cherbourg    no  False
49           49         0       3  female  18.00      1      0   17.8000        S   Third  woman       False  NaN  Southampton    no  False
50           50         0       3    male   7.00      4      1   39.6875        S   Third  child       False  NaN  Southampton    no  False
51           51         0       3    male  21.00      0      0    7.8000        S   Third    man        True  NaN  Southampton    no   True
52           52         1       1  female  49.00      1      0   76.7292        C   First  woman       False    D    Cherbourg   yes  False
53           53         1       2  female  29.00      1      0   26.0000        S  Second  woman       False  NaN  Southampton   yes  False
54           54         0       1    male  65.00      0      1   61.9792        C   First    man        True    B    Cherbourg    no  False
55           55         1       1    male    NaN      0      0   35.5000        S   First    man        True    C  Southampton   yes   True
56           56         1       2  female  21.00      0      0   10.5000        S  Second  woman       False  NaN  Southampton   yes   True
57           57         0       3    male  28.50      0      0    7.2292        C   Third    man        True  NaN    Cherbourg    no   True
58           58         1       2  female   5.00      1      2   27.7500        S  Second  child       False  NaN  Southampton   yes  False
59           59         0       3    male  11.00      5      2   46.9000        S   Third  child       False  NaN  Southampton    no  False
60           60         0       3    male  22.00      0      0    7.2292        C   Third    man        True  NaN    Cherbourg    no   True
61           61         1       1  female  38.00      0      0   80.0000      NaN   First  woman       False    B          NaN   yes   True
62           62         0       1    male  45.00      1      0   83.4750        S   First    man        True    C  Southampton    no  False
63           63         0       3    male   4.00      3      2   27.9000        S   Third  child       False  NaN  Southampton    no  False
64           64         0       1    male    NaN      0      0   27.7208        C   First    man        True  NaN    Cherbourg    no   True
65           65         1       3    male    NaN      1      1   15.2458        C   Third    man        True  NaN    Cherbourg   yes  False
66           66         1       2  female  29.00      0      0   10.5000        S  Second  woman       False    F  Southampton   yes   True
67           67         0       3    male  19.00      0      0    8.1583        S   Third    man        True  NaN  Southampton    no   True
68           68         1       3  female  17.00      4      2    7.9250        S   Third  woman       False  NaN  Southampton   yes  False
69           69         0       3    male  26.00      2      0    8.6625        S   Third    man        True  NaN  Southampton    no  False
70           70         0       2    male  32.00      0      0   10.5000        S  Second    man        True  NaN  Southampton    no   True
71           71         0       3  female  16.00      5      2   46.9000        S   Third  woman       False  NaN  Southampton    no  False
72           72         0       2    male  21.00      0      0   73.5000        S  Second    man        True  NaN  Southampton    no   True
73           73         0       3    male  26.00      1      0   14.4542        C   Third    man        True  NaN    Cherbourg    no  False
74           74         1       3    male  32.00      0      0   56.4958        S   Third    man        True  NaN  Southampton   yes   True
75           75         0       3    male  25.00      0      0    7.6500        S   Third    man        True    F  Southampton    no   True
76           76         0       3    male    NaN      0      0    7.8958        S   Third    man        True  NaN  Southampton    no   True
77           77         0       3    male    NaN      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
78           78         1       2    male   0.83      0      2   29.0000        S  Second  child       False  NaN  Southampton   yes  False
79           79         1       3  female  30.00      0      0   12.4750        S   Third  woman       False  NaN  Southampton   yes   True
80           80         0       3    male  22.00      0      0    9.0000        S   Third    man        True  NaN  Southampton    no   True
81           81         1       3    male  29.00      0      0    9.5000        S   Third    man        True  NaN  Southampton   yes   True
82           82         1       3  female    NaN      0      0    7.7875        Q   Third  woman       False  NaN   Queenstown   yes   True
83           83         0       1    male  28.00      0      0   47.1000        S   First    man        True  NaN  Southampton    no   True
84           84         1       2  female  17.00      0      0   10.5000        S  Second  woman       False  NaN  Southampton   yes   True
85           85         1       3  female  33.00      3      0   15.8500        S   Third  woman       False  NaN  Southampton   yes  False
86           86         0       3    male  16.00      1      3   34.3750        S   Third    man        True  NaN  Southampton    no  False
87           87         0       3    male    NaN      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
88           88         1       1  female  23.00      3      2  263.0000        S   First  woman       False    C  Southampton   yes  False
89           89         0       3    male  24.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
90           90         0       3    male  29.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
91           91         0       3    male  20.00      0      0    7.8542        S   Third    man        True  NaN  Southampton    no   True
92           92         0       1    male  46.00      1      0   61.1750        S   First    man        True    E  Southampton    no  False
93           93         0       3    male  26.00      1      2   20.5750        S   Third    man        True  NaN  Southampton    no  False
94           94         0       3    male  59.00      0      0    7.2500        S   Third    man        True  NaN  Southampton    no   True
95           95         0       3    male    NaN      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
96           96         0       1    male  71.00      0      0   34.6542        C   First    man        True    A    Cherbourg    no   True
97           97         1       1    male  23.00      0      1   63.3583        C   First    man        True    D    Cherbourg   yes  False
98           98         1       2  female  34.00      0      1   23.0000        S  Second  woman       False  NaN  Southampton   yes  False
99           99         0       2    male  34.00      1      0   26.0000        S  Second    man        True  NaN  Southampton    no  False
100         100         0       3  female  28.00      0      0    7.8958        S   Third  woman       False  NaN  Southampton    no   True
101         101         0       3    male    NaN      0      0    7.8958        S   Third    man        True  NaN  Southampton    no   True
102         102         0       1    male  21.00      0      1   77.2875        S   First    man        True    D  Southampton    no  False
103         103         0       3    male  33.00      0      0    8.6542        S   Third    man        True  NaN  Southampton    no   True
104         104         0       3    male  37.00      2      0    7.9250        S   Third    man        True  NaN  Southampton    no  False
105         105         0       3    male  28.00      0      0    7.8958        S   Third    man        True  NaN  Southampton    no   True
106         106         1       3  female  21.00      0      0    7.6500        S   Third  woman       False  NaN  Southampton   yes   True
107         107         1       3    male    NaN      0      0    7.7750        S   Third    man        True  NaN  Southampton   yes   True
108         108         0       3    male  38.00      0      0    7.8958        S   Third    man        True  NaN  Southampton    no   True
109         109         1       3  female    NaN      1      0   24.1500        Q   Third  woman       False  NaN   Queenstown   yes  False
110         110         0       1    male  47.00      0      0   52.0000        S   First    man        True    C  Southampton    no   True
111         111         0       3  female  14.50      1      0   14.4542        C   Third  child       False  NaN    Cherbourg    no  False
112         112         0       3    male  22.00      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
113         113         0       3  female  20.00      1      0    9.8250        S   Third  woman       False  NaN  Southampton    no  False
114         114         0       3  female  17.00      0      0   14.4583        C   Third  woman       False  NaN    Cherbourg    no   True
115         115         0       3    male  21.00      0      0    7.9250        S   Third    man        True  NaN  Southampton    no   True
116         116         0       3    male  70.50      0      0    7.7500        Q   Third    man        True  NaN   Queenstown    no   True
117         117         0       2    male  29.00      1      0   21.0000        S  Second    man        True  NaN  Southampton    no  False
118         118         0       1    male  24.00      0      1  247.5208        C   First    man        True    B    Cherbourg    no  False
119         119         0       3  female   2.00      4      2   31.2750        S   Third  child       False  NaN  Southampton    no  False
120         120         0       2    male  21.00      2      0   73.5000        S  Second    man        True  NaN  Southampton    no  False
121         121         0       3    male    NaN      0      0    8.0500        S   Third    man        True  NaN  Southampton    no   True
122         122         0       2    male  32.50      1      0   30.0708        C  Second    man        True  NaN    Cherbourg    no  False
123         123         1       2  female  32.50      0      0   13.0000        S  Second  woman       False    E  Southampton   yes   True
124         124         0       1    male  54.00      0      1   77.2875        S   First    man        True    D  Southampton    no  False
125         125         1       3    male  12.00      1      0   11.2417        C   Third  child       False  NaN    Cherbourg   yes  False
126         126         0       3    male    NaN      0      0    7.7500        Q   Third    man        True  NaN   Queenstown    no   True
127         127         1       3    male  24.00      0      0    7.1417        S   Third    man        True  NaN  Southampton   yes   True
128         128         1       3  female    NaN      1      1   22.3583        C   Third  woman       False    F    Cherbourg   yes  False
129         129         0       3    male  45.00      0      0    6.9750        S   Third    man        True  NaN  Southampton    no   True
130         130         0       3    male  33.00      0      0    7.8958        C   Third    man        True  NaN    Cherbourg    no   True
131         131         0       3    male  20.00      0      0    7.0500        S   Third    man        True  NaN  Southampton    no   True
132         132         0       3  female  47.00      1      0   14.5000        S   Third  woman       False  NaN  Southampton    no  False
133         133         1       2  female  29.00      1      0   26.0000        S  Second  woman       False  NaN  Southampton   yes  False
134         134         0       2    male  25.00      0      0   13.0000        S  Second    man        True  NaN  Southampton    no   True
135         135         0       2    male  23.00      0      0   15.0458        C  Second    man        True  NaN    Cherbourg    no   True
136         136         1       1  female  19.00      0      2   26.2833        S   First  woman       False    D  Southampton   yes  False
137         137         0       1    male  37.00      1      0   53.1000        S   First    man        True    C  Southampton    no  False
138         138         0       3    male  16.00      0      0    9.2167        S   Third    man        True  NaN  Southampton    no   True
139         139         0       1    male  24.00      0      0   79.2000        C   First    man        True    B    Cherbourg    no   True
140         140         0       3  female    NaN      0      2   15.2458        C   Third  woman       False  NaN    Cherbourg    no  False

In [ ]:
df.head() #prints first 5 rows

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.head(6) #prints top 6 rows

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.tail() #prints bottom 5 rows

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.tail(6) #prints bottom 6 rows

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
885,885,0,3,female,39.0,0,5,29.125,Q,Third,woman,False,NaN,Queenstown,no,False
886,886,0,2,male,27.0,0,0,13.000,S,Second,man,True,NaN,Southampton,no,True
887,887,1,1,female,19.0,0,0,30.000,S,First,woman,False,B,Southampton,yes,True
888,888,0,3,female,NaN,1,2,23.450,S,Third,woman,False,NaN,Southampton,no,False
889,889,1,1,male,26.0,0,0,30.000,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,male,32.0,0,0,7.750,Q,Third,man,True,NaN,Queenstown,no,True