What we have done so far:-

*   Handled missing values by dropping columns or filling values.
*   Remove duplicates

*   Encode data by mapping (for 2 categories or when we want to set priority)
*   Encode data using one hot encoding in case of multicategory.

*   Fix the data type to int.
*   Save cleaned data.

## Exploratory Data Analysis

*   Explore the data and do the analysis
*

In [ ]:
import pandas as pd
df=pd.read_csv('Titanic_cleaned.csv')
df.shape

(780, 17)

To count values of a column grouping by category (0 means 'no' and 1 means 'yes')

In [ ]:
df['survived'].value_counts()

survived
0    458
1    322
Name: count, dtype: int64

.describe() function describes the whole dataframe by giving the count, mean, standard deviation, min, 25%ile, 50%ile, 75%ile, max.

In [ ]:
df.describe()

,survived,pclass,sex,age,sibsp,parch,fare,class,adult_male,alive,alone,embarked_Q,embarked_S,who_man,who_woman,embark_town_Queenstown,embark_town_Southampton
count,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000
mean,0.412821,2.246154,0.625641,29.797600,0.525641,0.417949,34.829108,1.753846,0.574359,0.412821,0.566667,0.074359,0.726923,0.574359,0.320513,0.074359,0.726923
std,0.492657,0.854452,0.484267,13.708883,0.988046,0.838536,52.263440,0.854452,0.494757,0.492657,0.495854,0.262523,0.445826,0.494757,0.466973,0.262523,0.445826
min,0.000000,1.000000,0.000000,0.420000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,21.750000,0.000000,0.000000,8.050000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,3.000000,1.000000,29.699118,0.000000,0.000000,15.950000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000
75%,1.000000,3.000000,1.000000,36.000000,1.000000,1.000000,34.375000,3.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000
max,1.000000,3.000000,1.000000,80.000000,8.000000,6.000000,512.329200,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

To find how many males survived and how many females survived and how many males didn't survive and how many females didn't survive, we need to find the relation between the two columns 'survived' and 'sex'.

We use .crosstab() function with both columns as arguments. (works only for both columns being categorical data)

In [ ]:
pd.crosstab(df['sex'],df['survived'])

survived    0    1
sex
0          76  216
1         382  106

If we need the percentage of how many females survived and how many males survived, etc.

We need to normalize by index (divide the value by the sum of values in the row)

In [ ]:
pd.crosstab(df['sex'],df['survived'],normalize='index')

survived         0         1
sex
0         0.260274  0.739726
1         0.782787  0.217213

If we need the percentage of how many people who survived were females and how many people who survived were males, etc.

We need to normalize by column (divide the value by the sum of values in the column)

In [ ]:
pd.crosstab(df['sex'],df['survived'],normalize='columns')

survived         0         1
sex
0         0.165939  0.670807
1         0.834061  0.329193

Find relation between class and survived. class 1 means Third Class and class 3 means First class

In [ ]:
pd.crosstab(df['class'],df['survived'])

survived    0    1
class
1         300  104
2          81   83
3          77  135

In [ ]:
pd.crosstab(df['class'],df['survived'],normalize='index')

survived         0         1
class
1         0.742574  0.257426
2         0.493902  0.506098
3         0.363208  0.636792

For non-categorical columns or continuous data like 'age', we can't use .crosstab() as it will take all unique values of the column and categorise it based on that.

In [ ]:
pd.crosstab(df['age'],df['survived'])

survived  0  1
age
0.42      0  1
0.67      0  1
0.75      0  1
0.83      0  2
0.92      0  1
...      .. ..
70.00     2  0
70.50     1  0
71.00     2  0
74.00     1  0
80.00     0  1

[89 rows x 2 columns]

For continuous data, we use column.groupby(grouping_column). We select the column and apply a groupby on it based on the categorical column.

Hence, we use this when one column is continuous and one column is categorical and we need an aggregate value of the continuous column.

In [ ]:
df['age'].groupby(df['survived']).mean()

survived
0    30.707298
1    28.503682
Name: age, dtype: float64

In [ ]:
df.groupby('survived')['fare'].mean()

survived
0    24.026482
1    50.194333
Name: fare, dtype: float64